spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - OPTIONS
              - POST
              - PUT
              - DELETE

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always