version: '3.1'
services:
  users:
    build:
      context: .
    container_name: alpine_club_users
    image: alpine_club_users:latest
    ports:
      - "8081:8081"
    networks:
      - users-network
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:jammy
    volumes:
      - mongodb_data_users:/data/db
    networks:
      - users-network

networks:
  users-network:
    driver: bridge

volumes:
  mongodb_data_users: