version: '3.3'

services:
  articles:
    image: quarkus/articles-jvm:latest
    ports:
      - "8080:8080"
    depends_on:
      artemis:
        condition: service_healthy
    environment:
      - quarkus.mongodb.connection-string=mongodb://mongodb:27017/
      - quarkus.artemis.url=tcp://artemis:61616/
    networks:
      - app-network

  mongodb:
    image: mongo:jammy
    volumes:
      - mongodb_data_articles:/data/db
    networks:
      - app-network

  artemis:
    image: apache/activemq-artemis:latest-alpine
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "61616"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_articles:
