name: Users Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:jammy
        ports:
          - 27017:27017
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: maven

    - name: Build and test with Maven
      run: |
        cd Users
        mvn -B package --file pom.xml
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./Users
        file: Users/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/alp_club-articles:latest
