name: Users Build and Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:jammy
        ports:
          - 27017:27017
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        path: Users

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: maven

    - name: Build and test with Maven
      run: |
        cd Users/Users
        mvn -B package --file pom.xml
